const translations = {
    // English (Base)
    en: {
        page_title: "Mohammed EL BARAKA - Industrial Management & Data Science",
        nav_about: "About",
        nav_projects: "Projects",
        nav_skills: "Skills",
        nav_leadership: "Leadership",
        nav_contact: "Contact",
        hero_title: "Industrial Management,<br>& Data Science",
        hero_typing: ["Industrial Management", "Data Science"],
        hero_subtitle: "An Engineering graduate from EMINES-UM6P specializing in Industrial Management with a passion for Optimization, Data Science, and leveraging technology to solve real-world challenges.",
        hero_cta_button: "View My Work",
        about_title: "About Me",
        about_p1: "Hello! I'm Mohammed EL BARAKA, an Industrial Management engineering graduate from the prestigious Mohammed VI Polytechnic University (UM6P). My academic journey, beginning with an intensive program in Mathematics and Physics, has instilled in me a strong analytical and problem-solving mindset.",
        about_p2: "I am driven by the challenge of untangling complex problems, particularly through the application of Data Science, Machine Learning, and Optimization algorithms. My work philosophy is centered on bridging the gap between theoretical knowledge and practical application to create tangible results.",
        about_p3: "I am a proactive leader, fluent in Arabic, French, and English, and always eager to learn, collaborate, and apply my skills to impactful scenarios.",
        view_resume_button: "📄 View My Resume",
        projects_title: "My Projects",
        skills_title: "Technical Skills",
        leadership_title: "Leadership & Activities",
        contact_title: "Get In Touch",
        contact_subtitle: "I'm always open to discussing new projects, creative ideas, or opportunities. Let's connect.",
        contact_button: "Contact Me",
        footer_text: `© ${new Date().getFullYear()} Mohammed EL BARAKA. All Rights Reserved.`,
        contact_modal_title: "Contact Me",
        contact_modal_email: "Send an Email",
        contact_modal_whatsapp: "Message on WhatsApp",
        contact_modal_call: "Make a Call",
        project_button_report: "Report",
        project_button_presentation: "Presentation",
        project_button_explain: "✨ Explain",
        project_button_summarize: "✨ Summarize",
        modal_explaining_title: `✨ Explaining: {title}`,
        modal_summarizing_title: `✨ Summarizing: {title}`,
        modal_skill_projects_title: `🚀 Projects with {skill}`,
        modal_list_intro: `Here are the projects where I used <strong>{skill}</strong>:`,
        pdf_modal_title_report: `{title} Report`,
        pdf_modal_title_presentation: `{title} Presentation`,
        pdf_modal_title_resume: `My Resume`,
        projects: [
             { id: 'mental-health-analytics', title: 'Predictive Analytics for Student Mental Health', description: 'Developed predictive models using questionnaire and text data to assess student mental health, achieving high accuracy in predicting anxiety, depression, and stress levels.' },
             { id: 'red-fruit-optimization', title: 'Optimization of Red Fruit Production', description: 'Designed and implemented a Linear Programming model to maximize profit for red fruit production in greenhouses, considering various constraints and scenarios.' },
             { id: 'powerbi-dashboard', title: 'Bank Statement Integration with Power BI', description: 'Developed an interactive Power BI dashboard to integrate and visualize key financial metrics from bank statements and delivery notes for a connected data view.' },
             { id: 'rsa-cryptography', title: 'Attacks Against Shared Module RSA', description: 'Studied and simulated attacks against the RSA cryptosystem, focusing on vulnerabilities from shared modules to demonstrate cryptographic weaknesses.' },
             { id: 'biomedical-diffusion', title: 'Oxygen Diffusion in Pulmonary Acinus', description: 'Conducted a biomedical engineering project to model oxygen diffusion in the pulmonary acinus, resolving the 2D diffusion equation using numerical methods.' },
             { id: 'robotics-vision', title: 'Robotics and Image Detection', description: 'Developed a complete robotic system with image detection capabilities, from 3D modeling in SolidWorks to implementing image processing algorithms in Python.' }
        ],
        leadership: [
            { id: 'emines-junior-entreprise', title: 'Emines Junior Entreprise (EJE)', role: 'Sponsorship Manager', description: 'As Sponsorship Manager, my core responsibility is securing vital partnerships and sponsorships to power EJE\'s impactful portfolio of student hackathons. I actively seek sponsors for major events including the OP&X Hackathon, Strategic Consulting Hackathon (SCH), DataQuest Hackathon, and the Finance Hackathon. By connecting companies with these platforms, I help them engage Morocco\'s brightest students and fuel future talent development.' },
            { id: 'rubiks-club', title: "UM6P Rubik's Cube Club", role: "President", description: "As President, I led the club's activities, organized workshops, and fostered a community of problem-solvers." },
            { id: 'eplus-club', title: "E++ Club, EMINES", role: "Sponsoring Manager", description: "Secured sponsors for the National Data Science Competition (NDSC) and the Intelligent Robot Competition (IRC) by contacting potential partners, presenting proposals, and ensuring their support for both events." },
            { id: 'eastro-club', title: "E-Astronomy Club, EMINES", role: "Logistics Manager", description: "I orchestrated the logistics for observation nights and educational seminars, ensuring seamless availability of all equipment and resources, and served as an astronomy expert at the Moroccan Day of Mathematics." },
            { id: 'rotaract-club', title: "ROTARACT EMINES Club", role: "Communication & Content Manager", description: "I managed the club’s communication and content creation, developing engaging materials to promote the activities, events, and initiatives of Rotaract EMINES." },
            { id: 'pingpong-club', title: "UM6P Ping Pong Club", role: "Logistics Manager", description: "I organized tournaments and practice sessions, handling all logistical aspects from scheduling to equipment management." },
            { id: 'university-sports', title: "University Sports", role: "Player for Handball, Volleyball, and Football teams", description: "As an active member of multiple university sports teams, I developed strong teamwork, discipline, and leadership skills." }
        ],

        help_button: "How Can I Help You?",
        help_modal_title: "Describe Your Needs",
        help_modal_placeholder: "Tell me about the project, challenge, or role you have in mind. For example: 'I need someone to build a predictive model for customer data' or 'I am looking for a project manager with a technical background.'",
        help_modal_submit: "Analyze My Need",
        help_modal_response_title: "Here's How I Can Help",
        contact_button_after_ai: "Contact Mohammed",
    },
    // French
    fr: {
        page_title: "Mohammed EL BARAKA - Management Industrielle & Science des Données",
        nav_about: "À propos",
        nav_projects: "Projets",
        nav_skills: "Compétences",
        nav_leadership: "Leadership",
        nav_contact: "Contact",
        hero_title: "Management Industrielle,<br>& Science des Données",
        hero_typing: ["Management Industriel", "Science des Données"],
        hero_subtitle: "Ingénieur diplômé de l'EMINES-UM6P spécialisé en Management Industriel, passionné par l'Optimisation, la Science des Données et l'utilisation de la technologie pour résoudre des défis concrets.",
        hero_cta_button: "Voir mes travaux",
        about_title: "À propos de moi",
        about_p1: "Bonjour ! Je suis Mohammed EL BARAKA, ingénieur diplômé en Management Industriel de la prestigieuse Université Mohammed VI Polytechnique (UM6P). Mon parcours académique, débutant par un programme intensif en Mathématiques et Physique, m'a doté d'un solide esprit d'analyse et de résolution de problèmes.",
        about_p2: "Je suis motivé par le défi de démêler des problèmes complexes, notamment par l'application de la Science des Données, de l'Apprentissage Automatique et des algorithmes d'Optimisation. Ma philosophie de travail est de combler le fossé entre les connaissances théoriques et l'application pratique pour créer des résultats tangibles.",
        about_p3: "Je suis un leader proactif, parlant couramment l'arabe, le français et l'anglais, et toujours désireux d'apprendre, de collaborer et d'appliquer mes compétences à des scénarios percutants.",
        view_resume_button: "📄 Voir mon CV",
        projects_title: "Mes Projets",
        skills_title: "Compétences Techniques",
        leadership_title: "Leadership & Activités",
        contact_title: "Contactez-moi",
        contact_subtitle: "Je suis toujours ouvert à la discussion de nouveaux projets, d'idées créatives ou d'opportunités. Connectons-nous.",
        contact_button: "Me Contacter",
        footer_text: `© ${new Date().getFullYear()} Mohammed EL BARAKA. Tous droits réservés.`,
        contact_modal_title: "Me Contacter",
        contact_modal_email: "Envoyer un E-mail",
        contact_modal_whatsapp: "Message sur WhatsApp",
        contact_modal_call: "Passer un appel",
        project_button_report: "Rapport",
        project_button_presentation: "Présentation",
        project_button_explain: "✨ Expliquer",
        project_button_summarize: "✨ Résumer",
        modal_explaining_title: `✨ Explication : {title}`,
        modal_summarizing_title: `✨ Résumé : {title}`,
        modal_skill_projects_title: `🚀 Projets avec {skill}`,
        modal_list_intro: `Voici les projets où j'ai utilisé <strong>{skill}</strong> :`,
        pdf_modal_title_report: `Rapport - {title}`,
        pdf_modal_title_presentation: `Présentation - {title}`,
        pdf_modal_title_resume: `Mon CV`,
        projects: [
            { id: 'mental-health-analytics', title: 'Analyse Prédictive de la Santé Mentale des Étudiants', description: 'Développement de modèles prédictifs utilisant des données de questionnaires et textuelles pour évaluer la santé mentale des étudiants, atteignant une grande précision dans la prédiction de l\'anxiété, la dépression et le stress.' },
            { id: 'red-fruit-optimization', title: 'Optimisation de la Production de Fruits Rouges', description: 'Conception et mise en œuvre d\'un modèle de programmation linéaire pour maximiser le profit de la production de fruits rouges en serre, en tenant compte de diverses contraintes et scénarios.' },
            { id: 'powerbi-dashboard', title: 'Intégration de Relevés Bancaires avec Power BI', description: 'Développement d\'un tableau de bord Power BI interactif pour intégrer et visualiser les indicateurs financiers clés des relevés bancaires et des bons de livraison pour une vue de données connectée.' },
            { id: 'rsa-cryptography', title: 'Attaque contre le RSA à Module Partagé', description: 'Étude et simulation d\'attaques contre le cryptosystème RSA, en se concentrant sur les vulnérabilités des modules partagés pour démontrer les faiblesses cryptographiques.' },
            { id: 'biomedical-diffusion', title: 'Diffusion d\'Oxygène dans l\'Acinus Pulmonaire', description: 'Réalisation d\'un projet d\'ingénierie biomédicale pour modéliser la diffusion d\'oxygène dans l\'acinus pulmonaire, en résolvant l\'équation de diffusion 2D par des méthodes numériques.' },
            { id: 'robotics-vision', title: 'Robotique et Détection d\'Images', description: 'Développement d\'un système robotique complet avec des capacités de détection d\'images, de la modélisation 3D sur SolidWorks à la mise en œuvre d\'algorithmes de traitement d\'images en Python.' }
        ],
        leadership: [
            { id: 'emines-junior-entreprise', title: 'Emines Junior Entreprise (EJE)', role: 'Responsable Sponsoring', description: 'En tant que Responsable Sponsoring, ma responsabilité principale est de sécuriser des partenariats et des sponsorings essentiels pour alimenter le portefeuille percutant de hackathons étudiants d\'EJE. Je recherche activement des sponsors pour des événements majeurs tels que le Hackathon OP&X, le Hackathon de Conseil Stratégique (SCH), le Hackathon DataQuest et le Hackathon Finance. En connectant les entreprises à ces plateformes, je les aide à interagir avec les étudiants les plus brillants du Maroc et à stimuler le développement des futurs talents.' },
            { id: 'rubiks-club', title: "Club de Rubik's Cube UM6P", role: "Président", description: "En tant que Président, j'ai dirigé les activités du club, organisé des ateliers et encouragé une communauté de solutionneurs de problèmes." },
            { id: 'eplus-club', title: "Club E++, EMINES", role: "Responsable Sponsoring", description: "Obtenu des sponsors pour le National Data Science Competition (NDSC) et l’Intelligent Robot Competition (IRC) en contactant des partenaires potentiels, en présentant des propositions et en assurant leur soutien aux deux événements." },
            { id: 'eastro-club', title: "Club E-Astronomie, EMINES", role: "Responsable Logistique", description: "J’ai orchestré la logistique des soirées d’observation et des séminaires éducatifs, en veillant à la disponibilité sans faille de tout l’équipement et des ressources, et j’ai participé en tant qu’expert en astronomie à la Journée marocaine des mathématiques." },
            { id: 'rotaract-club', title: "Club ROTARACT EMINES", role: "Responsable Communication & Contenu", description: "J’ai géré la communication du club et la création de contenu, en concevant des supports captivants pour promouvoir les activités, événements et initiatives du Rotaract EMINES." },
            { id: 'pingpong-club', title: "Club de Ping Pong UM6P", role: "Responsable Logistique", description: "J'ai organisé des tournois et des séances d'entraînement, gérant tous les aspects logistiques, de la planification à la gestion du matériel." },
            { id: 'university-sports', title: "Sports Universitaires", role: "Joueur des équipes de Handball, Volleyball et Football", description: "En tant que membre actif de plusieurs équipes sportives universitaires, j'ai développé de solides compétences en travail d'équipe, discipline et leadership." }
        ],

        help_button: "Comment puis-je vous aider ?",
        help_modal_title: "Décrivez vos besoins",
        help_modal_placeholder: "Parlez-moi du projet, du défi ou du rôle que vous avez en tête. Exemple : 'J'ai besoin de quelqu'un pour créer un modèle prédictif pour les données clients' ou 'Je recherche un chef de projet avec un bagage technique.'",
        help_modal_submit: "Analyser mon besoin",
        help_modal_response_title: "Voici comment je peux aider",
        contact_button_after_ai: "Contacter Mohammed"
    },
    // Arabic
    ar: {
        page_title: "محمد البركا - التدبير الصناعي وعلوم البيانات",
        nav_about: "عني",
        nav_projects: "مشاريعي",
        nav_skills: "مهاراتي",
        nav_leadership: "القيادة",
        nav_contact: "تواصل",
        hero_title: "الإدارة الصناعية،<br>وعلوم البيانات",
        hero_typing: ["الإدارة الصناعية", "علوم البيانات"],
        hero_subtitle: "مهندس خريج EMINES متخصص في التدبير الصناعي وشغوف بعلوم البيانات وتسخير التكنولوجيا لمواجهة تحديات العالم الحقيقي.",
        hero_cta_button: "اكتشف أعمالي",
        about_title: "عني",
        about_p1: "مرحباً! أنا محمد البركا، مهندس خريج في التدبير الصناعي من جامعة محمد السادس للفنون التطبيقية (UM6P) المرموقة. رحلتي الأكاديمية، التي بدأت ببرنامج مكثف في الرياضيات والفيزياء، غرست فيّ عقلية تحليلية قوية وقدرة على حل المشكلات.",
        about_p2: "يدفعني تحدي حل المشكلات المعقدة، خاصة من خلال تطبيق علوم البيانات والتعلم الآلي وخوارزميات التحسين. تتمحور فلسفة عملي حول سد الفجوة بين المعرفة النظرية والتطبيق العملي لتحقيق نتائج ملموسة.",
        about_p3: "أنا قائد استباقي، وأتقن اللغات العربية والفرنسية والإنجليزية، وأنا حريص دائمًا على التعلم والتعاون وتطبيق مهاراتي في سيناريوهات مؤثرة.",
        view_resume_button: "📄 عرض سيرتي الذاتية",
        projects_title: "مشاريعي",
        skills_title: "المهارات التقنية",
        leadership_title: "القيادة والأنشطة",
        contact_title: "تواصل معي",
        contact_subtitle: "أنا منفتح دائمًا لمناقشة المشاريع الجديدة أو الأفكار الإبداعية أو الفرص. لنتواصل.",
        contact_button: "تواصل معي",
        footer_text: `© ${new Date().getFullYear()} محمد البركا. كل الحقوق محفوظة.`,
        contact_modal_title: "تواصل معي",
        contact_modal_email: "أرسل بريدًا إلكترونيًا",
        contact_modal_whatsapp: "راسلني على واتساب",
        contact_modal_call: "أجرِ مكالمة",
        project_button_report: "التقرير",
        project_button_presentation: "التقديم",
        project_button_explain: "✨ اشرح",
        project_button_summarize: "✨ لخّص",
        modal_explaining_title: `✨ شرح: {title}`,
        modal_summarizing_title: `✨ تلخيص: {title}`,
        modal_skill_projects_title: `🚀 مشاريع تستخدم {skill}`,
        modal_list_intro: `هذه هي المشاريع التي استخدمت فيها <strong>{skill}</strong>:`,
        pdf_modal_title_report: `تقرير - {title}`,
        pdf_modal_title_presentation: `عرض تقديمي - {title}`,
        pdf_modal_title_resume: `سيرتي الذاتية`,
        projects: [
             { id: 'mental-health-analytics', title: 'تحليلات تنبؤية للصحة النفسية للطلاب', description: 'تطوير نماذج تنبؤية باستخدام بيانات الاستبيانات والنصوص لتقييم الصحة النفسية للطلاب، وتحقيق دقة عالية في التنبؤ بمستويات القلق والاكتئاب والتوتر.' },
             { id: 'red-fruit-optimization', title: 'تحسين إنتاج الفواكه الحمراء', description: 'تصميم وتنفيذ نموذج برمجة خطية لتعظيم الربح من إنتاج الفاكهة الحمراء في البيوت المحمية، مع مراعاة مختلف القيود والسيناريوهات.' },
             { id: 'powerbi-dashboard', title: 'دمج كشوف الحسابات البنكية مع Power BI', description: 'تطوير لوحة تحكم Power BI تفاعلية لدمج وتصور المقاييس المالية الرئيسية من كشوف الحسابات البنكية ومذكرات التسليم للحصول على عرض بيانات متصل.' },
             { id: 'rsa-cryptography', title: 'هجمات ضد RSA ذات المعامل المشترك', description: 'دراسة ومحاكاة الهجمات ضد نظام التشفير RSA، مع التركيز على نقاط الضعف الناتجة عن الوحدات المشتركة لإظهار نقاط الضعف في التشفير.' },
             { id: 'biomedical-diffusion', title: 'انتشار الأكسجين في الحويصلات الرئوية', description: 'إجراء مشروع هندسة طبية حيوية لنمذجة انتشار الأكسجين في الحويصلات الرئوية، وحل معادلة الانتشار ثنائية الأبعاد باستخدام الطرق العددية.' },
             { id: 'robotics-vision', title: 'الروبوتات وكشف الصور', description: 'تطوير نظام روبوتي كامل مع إمكانات كشف الصور، من النمذجة ثلاثية الأبعاد في SolidWorks إلى تنفيذ خوارزميات معالجة الصور في Python.' }
        ],
        leadership: [
            { id: 'emines-junior-entreprise', title: 'EJE', role: 'مدير الرعاية', description: 'بصفتي مدير الرعاية، تتمثل مسؤوليتي الأساسية في تأمين الشراكات والرعاية الحيوية لدعم محفظة EJE المؤثرة من مسابقات البرمجة الطلابية. أبحث عن رعاة للأحداث الكبرى بما في ذلك مسابقة البرمجة OP&X Hackathon ومسابقة البرمجة الاستشارية الاستراتيجية (SCH) ومسابقة البرمجة DataQuest Hackathon ومسابقة البرمجة المالية Finance Hackathon. من خلال ربط الشركات بهذه المنصات، أساعدها على جذب ألمع الطلاب المغاربة ودعم تنمية المواهب المستقبلية.' },
            { id: 'rubiks-club', title: "نادي مكعب روبيك UM6P", role: "رئيس", description: "بصفتي رئيسًا، قمت بقيادة أنشطة النادي، وتنظيم ورش عمل، وتعزيز مجتمع من حلالي المشكلات." },
            { id: 'eplus-club', title: "نادي E++، EMINES", role: "مدير الرعاية", description: "حصلت على رعاة للمسابقة الوطنية لعلوم البيانات (NDSC) ومسابقة الروبوت الذكي (IRC) من خلال التواصل مع شركاء محتملين، وعرض المقترحات، وضمان دعمهم لكلا الحدثين." },
            { id: 'eastro-club', title: "نادي، EMINES ASTRO ", role: "مدير الخدمات اللوجستية", description: "نظمت الخدمات اللوجستية لليالي المراقبة والندوات التعليمية، مؤكدًا توفر جميع المعدات والموارد بسلاسة، وشاركت كخبير في علم الفلك في اليوم المغربي للرياضيات." },
            { id: 'rotaract-club', title: "نادي ROTARACT EMINES", role: "مدير الاتصالات والمحتوى", description: "لقد أدرت تواجد النادي على وسائل التواصل الاجتماعي وأنشأت محتوى جذابًا للترويج لمشاريع خدمة المجتمع لدينا." },
            { id: 'pingpong-club', title: "نادي تنس الطاولة UM6P", role: "مدير الخدمات اللوجستية", description: "نظمت بطولات وجلسات تدريبية، وتوليت جميع الجوانب اللوجستية من الجدولة إلى إدارة المعدات." },
            { id: 'university-sports', title: "الرياضة الجامعية", role: "لاعب في فرق كرة اليد والكرة الطائرة وكرة القدم", description: "كعضو نشط في العديد من الفرق الرياضية الجامعية، طورت مهارات قوية في العمل الجماعي والانضباط والقيادة. " }
        ],

        help_button: "كيف يمكنني المساعدة؟",
        help_modal_title: "صف احتياجاتك",
        help_modal_placeholder: "أخبرني عن المشروع أو التحدي أو الدور الذي تفكر فيه. على سبيل المثال: 'أحتاج إلى شخص لبناء نموذج تنبؤي لبيانات العملاء' أو 'أبحث عن مدير مشروع بخلفية تقنية.'",
        help_modal_submit: "حلل احتياجي",
        help_modal_response_title: "إليك كيف يمكنني المساعدة",
        contact_button_after_ai: "تواصل مع محمد"
    },
    // Spanish
    es: {
        page_title: "Mohammed EL BARAKA - Gestión Industrial y Ciencia de Datos",
        nav_about: "Sobre mí",
        nav_projects: "Proyectos",
        nav_skills: "Habilidades",
        nav_leadership: "Liderazgo",
        nav_contact: "Contacto",
        hero_title: "Gestión Industrial,<br>y Ciencia de Datos",
        hero_typing: ["Gestión Industrial", "Ciencia de Datos"],
        hero_subtitle: "Graduado en Ingeniería de EMINES-UM6P especializado en Gestión Industrial con pasión por la Optimización, la Ciencia de Datos y el aprovechamiento de la tecnología para resolver desafíos del mundo real.",
        hero_cta_button: "Ver mi trabajo",
        about_title: "Sobre Mí",
        about_p1: "¡Hola! Soy Mohammed EL BARAKA, un graduado en ingeniería de Gestión Industrial de la prestigiosa Universidad Politécnica Mohammed VI (UM6P). Mi trayectoria académica, que comenzó con un programa intensivo en Matemáticas y Física, me ha inculcado una fuerte mentalidad analítica y de resolución de problemas.",
        about_p2: "Me impulsa el desafío de desentrañar problemas complejos, particularmente a través de la aplicación de la Ciencia de Datos, el Aprendizaje Automático y los algoritmos de Optimización. Mi filosofía de trabajo se centra en cerrar la brecha entre el conocimiento teórico y la aplicación práctica para crear resultados tangibles.",
        about_p3: "Soy un líder proactivo, con fluidez en árabe, francés e inglés, y siempre estoy ansioso por aprender, colaborar y aplicar mis habilidades en escenarios de impacto.",
        view_resume_button: "📄 Ver mi CV",
        projects_title: "Mis Proyectos",
        skills_title: "Habilidades Técnicas",
        leadership_title: "Liderazgo y Actividades",
        contact_title: "Ponte en Contacto",
        contact_subtitle: "Siempre estoy abierto a discutir nuevos proyectos, ideas creativas u oportunidades. Conectemos.",
        contact_button: "Contáctame",
        footer_text: `© ${new Date().getFullYear()} Mohammed EL BARAKA. Todos los derechos reservados.`,
        contact_modal_title: "Contáctame",
        contact_modal_email: "Enviar un Correo",
        contact_modal_whatsapp: "Mensaje en WhatsApp",
        contact_modal_call: "Hacer una Llamada",
        project_button_report: "Informe",
        project_button_presentation: "Presentación",
        project_button_explain: "✨ Explicar",
        project_button_summarize: "✨ Resumir",
        modal_explaining_title: `✨ Explicando: {title}`,
        modal_summarizing_title: `✨ Resumiendo: {title}`,
        modal_skill_projects_title: `🚀 Proyectos con {skill}`,
        modal_list_intro: `Aquí están los proyectos donde usé <strong>{skill}</strong>:`,
        pdf_modal_title_report: `Informe - {title}`,
        pdf_modal_title_presentation: `Presentación - {title}`,
        pdf_modal_title_resume: `Mi Currículum`,
        projects: [
            { id: 'mental-health-analytics', title: 'Análisis Predictivo de la Salud Mental Estudiantil', description: 'Desarrollé modelos predictivos utilizando datos de cuestionarios y texto para evaluar la salud mental de los estudiantes, logrando una alta precisión en la predicción de los niveles de ansiedad, depresión y estrés.' },
            { id: 'red-fruit-optimization', title: 'Optimización de la Producción de Frutos Rojos', description: 'Diseñé e implementé un modelo de Programación Lineal para maximizar el beneficio de la producción de frutos rojos en invernaderos, considerando diversas restricciones y escenarios.' },
            { id: 'powerbi-dashboard', title: 'Integración de Extractos Bancarios con Power BI', description: 'Desarrollé un panel de Power BI interactivo para integrar y visualizar métricas financieras clave de extractos bancarios y albaranes de entrega para una vista de datos conectada.' },
            { id: 'rsa-cryptography', title: 'Ataques Contra RSA de Módulo Compartido', description: 'Estudié y simulé ataques contra el criptosistema RSA, centrándome en las vulnerabilidades de los módulos compartidos para demostrar las debilidades criptográficas.' },
            { id: 'biomedical-diffusion', title: 'Difusión de Oxígeno en el Acino Pulmonar', description: 'Realicé un proyecto de ingeniería biomédica para modelar la difusión de oxígeno en el acino pulmonar, resolviendo la ecuación de difusión 2D utilizando métodos numéricos.' },
            { id: 'robotics-vision', title: 'Robótica y Detección de Imágenes', description: 'Desarrollé un sistema robótico completo con capacidades de detección de imágenes, desde el modelado 3D en SolidWorks hasta la implementación de algoritmos de procesamiento de imágenes en Python.' }
        ],
        leadership: [
            { id: 'emines-junior-entreprise', title: 'Emines Junior Entreprise (EJE)', role: 'Gerente de Patrocinios', description: 'Como Gerente de Patrocinios, mi responsabilidad principal es asegurar alianzas y patrocinios vitales para impulsar el impactante portafolio de hackathons estudiantiles de EJE. Busco activamente patrocinadores para eventos importantes como el Hackathon OP&X, el Hackathon de Consultoría Estratégica (SCH), el Hackathon DataQuest y el Hackathon de Finanzas. Al conectar empresas con estas plataformas, les ayudo a interactuar con los estudiantes más brillantes de Marruecos y a fomentar el desarrollo de futuros talentos.' },
            { id: 'rubiks-club', title: "Club de Cubo de Rubik UM6P", role: "Presidente", description: "Como Presidente, lideré las actividades del club, organicé talleres y fomenté una comunidad de solucionadores de problemas." },
            { id: 'eplus-club', title: "Club E++, EMINES", role: "Gerente de Patrocinios", description: "Obtuve patrocinadores para la Competencia Nacional de Ciencia de Datos (NDSC) y la Competencia de Robots Inteligentes (IRC) contactando a socios potenciales, presentando propuestas y asegurando su apoyo para ambos eventos." },
            { id: 'eastro-club', title: "Club de E-Astronomía, EMINES", role: "Gerente de Logística", description: "Coordiné la logística de noches de observación y seminarios educativos, garantizando la disponibilidad impecable de todo el equipo y recursos, y participé como experto en astronomía en el Día Marroquí de las Matemáticas." },
            { id: 'rotaract-club', title: "Club ROTARACT EMINES", role: "Gerente de Comunicación y Contenido", description: "Gestioné la comunicación del club y la creación de contenido, desarrollando materiales atractivos para promover las actividades, eventos e iniciativas de Rotaract EMINES." },
            { id: 'pingpong-club', title: "Club de Ping Pong UM6P", role: "Gerente de Logística", description: "Organicé torneos y sesiones de práctica, manejando todos los aspectos logísticos desde la programación hasta la gestión de equipos." },
            { id: 'university-sports', title: "Deportes Universitarios", role: "Jugador de los equipos de Balonmano, Voleibol y Fútbol", description: "Como miembro activo de múltiples equipos deportivos universitarios, desarrollé sólidas habilidades de trabajo en equipo, disciplina y liderazgo." }
        ],

        help_button: "¿Cómo puedo ayudarte?",
        help_modal_title: "Describe tus necesidades",
        help_modal_placeholder: "Háblame sobre el proyecto, desafío o rol que tienes en mente. Por ejemplo: 'Necesito a alguien que construya un modelo predictivo para datos de clientes' o 'Estoy buscando un gerente de proyectos con experiencia técnica.'",
        help_modal_submit: "Analizar mi necesidad",
        help_modal_response_title: "Así es como puedo ayudar",
        contact_button_after_ai: "Contactar a Mohammed"
    },
    // Mandarin Chinese
    zh: {
        page_title: "Mohammed EL BARAKA - 工业管理与数据科学",
        nav_about: "关于",
        nav_projects: "项目",
        nav_skills: "技能",
        nav_leadership: "领导力",
        nav_contact: "联系",
        hero_title: "工业管理<br>与数据科学",
        hero_typing: ["工业管理", "数据科学"],
        hero_subtitle: "一名EMINES-UM6P的工程专业毕业生，主修工业管理，热衷于优化、数据科学，并利用技术解决现实世界中的挑战。(Pinyin: Yī míng EMINES-UM6P de gōngchéng zhuānyè bìyèshēng, zhǔ xiū gōngyè guǎnlǐ, rèzhōng yú yōuhuà, shùjù kēxué, bìng lìyòng jìshù jiějué xiànshí shìjiè zhōng de tiǎozhàn.)",
        hero_cta_button: "查看我的作品",
        about_title: "关于我",
        about_p1: "你好！我是Mohammed EL BARAKA，是著名的穆罕默德六世理工大学（UM6P）工业管理工程专业的 graduate。我的学术旅程始于数学和物理的强化课程，这培养了我强大的分析和解决问题的思维能力。(Pinyin: Nǐ hǎo! Wǒ shì Mohammed EL BARAKA, shì zhùmíng de Mùhǎnmòdé liùshì lǐgōng dàxué (UM6P) gōngyè guǎnlǐ gōngchéng zhuānyè de bìyèshēng. Wǒ de xuéshù lǚchéng shǐ yú shùxué hé wùlǐ de qiánghuà kèchéng, zhè péiyǎngle wǒ qiángdà de fēnxī hé jiějué wèntí de sīwéi nénglì.)",
        about_p2: "我被解决复杂问题的挑战所驱动，特别是通过应用数据科学、机器学习和优化算法。我的工作理念是弥合理论知识与实际应用之间的差距，以创造切实的成果。(Pinyin: Wǒ bèi jiějué fùzá wèntí de tiǎozhàn suǒ qūdòng, tèbié ISO tōngguò yìngyòng shùjù kēxué, jīqì xuéxí hé yōuhuà suànfǎ. Wǒ de gōngzuò lǐniàn shì míhé lǐlùn zhīshì yǔ shíjì yìngyòng zhī jiān de chājù, yǐ chuàngzào qièshí de chéngguǒ.)",
        about_p3: "我是一个积极主动的领导者，精通阿拉伯语、法语和英语，并总是渴望学习、合作，并将我的技能应用于有影响力的场景中。(Pinyin: Wǒ shì yīgè jījí zhǔdòng de lǐngdǎo zhě, jīngtōng ā lābó yǔ, fǎyǔ hé yīngyǔ, bìng zǒng shì kěwàng xuéxí, hézuò, bìng jiāng wǒ de jìnéng yìngyòng yú yǒu yǐngxiǎng lì de chǎngjǐng zhōng.)",
        view_resume_button: "📄 查看我的简历",
        projects_title: "我的项目",
        skills_title: "技术技能",
        leadership_title: "领导力与活动",
        contact_title: "联系我",
        contact_subtitle: "我随时乐意讨论新项目、创意或机会。让我们建立联系吧。",
        contact_button: "联系我",
        footer_text: `© ${new Date().getFullYear()} Mohammed EL BARAKA. 版权所有。`,
        contact_modal_title: "联系我",
        contact_modal_email: "发送电子邮件",
        contact_modal_whatsapp: "在WhatsApp上留言",
        contact_modal_call: "拨打电话",
        project_button_report: "报告",
        project_button_presentation: "演示",
        project_button_explain: "✨ 解释",
        project_button_summarize: "✨ 总结",
        modal_explaining_title: `✨ 解释：{title}`,
        modal_summarizing_title: `✨ 总结：{title}`,
        modal_skill_projects_title: `🚀 使用 {skill} 的项目`,
        modal_list_intro: `这是我使用 <strong>{skill}</strong> 的项目：`,
        pdf_modal_title_report: `报告 - {title}`,
        pdf_modal_title_presentation: `演示 - {title}`,
        pdf_modal_title_resume: `我的简历`,
        projects: [
            { id: 'mental-health-analytics', title: '学生心理健康预测分析', description: '使用问卷和文本数据开发预测模型来评估学生的心理健康状况，在预测焦虑、抑郁和压力水平方面实现了高准确性。' },
            { id: 'red-fruit-optimization', title: '红果生产优化', description: '设计并实施了一个线性规划模型，以最大化温室中红果生产的利润，同时考虑了各种约束和情景。' },
            { id: 'powerbi-dashboard', title: '银行对账单与Power BI集成', description: '开发了一个交互式Power BI仪表板，用于整合和可视化银行对账单和交货单中的关键财务指标，以实现连接的数据视图。' },
            { id: 'rsa-cryptography', title: '针对共享模数RSA的攻击', description: '研究并模拟了针对RSA密码系统的攻击，重点关注共享模数带来的漏洞，以展示密码学弱点。' },
            { id: 'biomedical-diffusion', title: '肺腺泡中的氧气扩散', description: '进行了一个生物医学工程项目，对肺腺泡中的氧气扩散进行建模，使用数值方法求解二维扩散方程。' },
            { id: 'robotics-vision', title: '机器人技术与图像检测', description: '开发了一个完整的具有图像检测功能的机器人系统，从在SolidWorks中进行3D建模到在Python中实现图像处理算法。' }
        ],
        leadership: [
            { id: 'emines-junior-entreprise', title: 'Emines Junior Entreprise (EJE)', role: '赞助经理', description: '作为赞助经理，我的核心职责是确保重要的合作伙伴关系和赞助，为EJE富有影响力的学生黑客马拉松系列活动提供支持。我积极为主要活动寻找赞助商，包括OP&X黑客马拉松、战略咨询黑客马拉松（SCH）、DataQuest黑客马拉松以及金融黑客马拉松。通过将公司与这些平台联系起来，我帮助他们接触到摩洛哥最优秀的学生，并为未来的人才发展提供动力。' },
            { id: 'rubiks-club', title: "UM6P 魔方俱乐部", role: "主席", description: "作为主席，我领导了俱乐部的活动，组织了研讨会，并培养了一个解决问题的社区。" },
            { id: 'eplus-club', title: "E++ 俱乐部, EMINES", role: "赞助经理", description: "通过联系潜在合作伙伴、提交提案并确保他们对两项赛事（国家数据科学竞赛（NDSC）和智能机器人竞赛（IRC））的支持，成功获得了赞助。" },
            { id: 'eastro-club', title: "E-天文学俱乐部, EMINES", role: "后勤经理", description: "我协调了观测之夜和教育研讨会的后勤工作，确保所有设备和资源的无缝可用，并作为天文学专家参加了摩洛哥数学日。" },
            { id: 'rotaract-club', title: "ROTARACT EMINES 俱乐部", role: "沟通与内容经理", description: "我管理了俱乐部的沟通和内容创作，开发引人入胜的材料，以推广Rotaract EMINES的活动、赛事和倡议。" },
            { id: 'pingpong-club', title: "UM6P 乒乓球俱乐部", role: "后勤经理", description: "我组织了比赛和练习赛，处理从日程安排到设备管理的所有后勤方面。 " },
            { id: 'university-sports', title: "大学体育", role: "手球、排球和足球队队员", description: "作为多个大学运动队的活跃成员，我培养了强大的团队合作、纪律和领导能力。 " }
        ],

        help_button: "我能为您做些什么？",
        help_modal_title: "描述您的需求",
        help_modal_placeholder: "请告诉我您心目中的项目、挑战或职位。例如：'我需要有人为客户数据建立一个预测模型'或'我正在寻找一位有技术背景的项目经理。'",
        help_modal_submit: "分析我的需求",
        help_modal_response_title: "我可以这样帮助您",
        contact_button_after_ai: "联系 Mohammed"
    },
    // Portuguese
    pt: {
        page_title: "Mohammed EL BARAKA - Gestão Industrial & Ciência de Dados",
        nav_about: "Sobre",
        nav_projects: "Projetos",
        nav_skills: "Habilidades",
        nav_leadership: "Liderança",
        nav_contact: "Contato",
        hero_title: "Gestão Industrial,<br>& Ciência de Dados",
        hero_typing: ["Gestão Industrial", "Ciência de Dados"],
        hero_subtitle: "Graduado em Engenharia pela EMINES-UM6P, especializado em Gestão Industrial, com paixão por Otimização, Ciência de Dados e por alavancar a tecnologia para resolver desafios do mundo real.",
        hero_cta_button: "Ver Meus Trabalhos",
        about_title: "Sobre Mim",
        about_p1: "Olá! Sou Mohammed EL BARAKA, um graduado em engenharia de Gestão Industrial pela prestigiosa Universidade Politécnica Mohammed VI (UM6P). Minha jornada acadêmica, começando com um programa intensivo em Matemática e Física, incutiu em mim uma forte mentalidade analítica e de resolução de problemas.",
        about_p2: "Sou motivado pelo desafio de desvendar problemas complexos, particularmente através da aplicação de Ciência de Dados, Aprendizado de Máquina e algoritmos de Otimização. Minha filosofia de trabalho está centrada em preencher a lacuna entre o conhecimento teórico e a aplicação prática para criar resultados tangíveis.",
        about_p3: "Sou um líder proativo, fluente em árabe, francês e inglês, e sempre ansioso para aprender, colaborar e aplicar minhas habilidades em cenários de impacto.",
        view_resume_button: "📄 Ver Meu Currículo",
        projects_title: "Meus Projetos",
        skills_title: "Habilidades Técnicas",
        leadership_title: "Liderança & Atividades",
        contact_title: "Entre em Contato",
        contact_subtitle: "Estou sempre aberto a discutir novos projetos, ideias criativas ou oportunidades. Vamos nos conectar.",
        contact_button: "Contate-me",
        footer_text: `© ${new Date().getFullYear()} Mohammed EL BARAKA. Todos os direitos reservados.`,
        contact_modal_title: "Contate-me",
        contact_modal_email: "Enviar um E-mail",
        contact_modal_whatsapp: "Mensagem no WhatsApp",
        contact_modal_call: "Fazer uma Chamada",
        project_button_report: "Relatório",
        project_button_presentation: "Apresentação",
        project_button_explain: "✨ Explicar",
        project_button_summarize: "✨ Resumir",
        modal_explaining_title: `✨ Explicando: {title}`,
        modal_summarizing_title: `✨ Resumindo: {title}`,
        modal_skill_projects_title: `🚀 Projetos com {skill}`,
        modal_list_intro: `Aqui estão os projetos onde usei <strong>{skill}</strong>:`,
        pdf_modal_title_report: `Relatório - {title}`,
        pdf_modal_title_presentation: `Apresentação - {title}`,
        pdf_modal_title_resume: `Meu Currículo`,
        projects: [
            { id: 'mental-health-analytics', title: 'Análise Preditiva da Saúde Mental de Estudantes', description: 'Desenvolvi modelos preditivos usando dados de questionários e textos para avaliar a saúde mental dos estudantes, alcançando alta precisão na previsão de níveis de ansiedade, depressão e estresse.' },
            { id: 'red-fruit-optimization', title: 'Otimização da Produção de Frutas Vermelhas', description: 'Projetei e implementei um modelo de Programação Linear para maximizar o lucro da produção de frutas vermelhas em estufas, considerando várias restrições e cenários.' },
            { id: 'powerbi-dashboard', title: 'Integração de Extratos Bancários com Power BI', description: 'Desenvolvi um painel interativo do Power BI para integrar e visualizar métricas financeiras chave de extratos bancários e notas de entrega para uma visão de dados conectada.' },
            { id: 'rsa-cryptography', title: 'Ataques Contra RSA de Módulo Compartilhado', description: 'Estudei e simulei ataques contra o criptossistema RSA, focando nas vulnerabilidades de módulos compartilhados para demonstrar fraquezas criptográficas.' },
            { id: 'biomedical-diffusion', title: 'Difusão de Oxigênio no Ácino Pulmonar', description: 'Conduzi um projeto de engenharia biomédica para modelar a difusão de oxigênio no ácino pulmonar, resolvendo a equação de difusão 2D usando métodos numéricos.' },
            { id: 'robotics-vision', title: 'Robótica e Detecção de Imagem', description: 'Desenvolvi um sistema robótico completo com capacidades de detecção de imagem, desde a modelagem 3D no SolidWorks até a implementação de algoritmos de processamento de imagem em Python.' }
        ],
        leadership: [
            { id: 'emines-junior-entreprise', title: 'Emines Junior Entreprise (EJE)', role: 'Gerente de Patrocínios', description: 'Como Gerente de Patrocínios, minha principal responsabilidade é garantir parcerias e patrocínios vitais para impulsionar o portfólio impactante de hackathons estudantis da EJE. Busco ativamente patrocinadores para grandes eventos, incluindo o Hackathon OP&X, o Hackathon de Consultoria Estratégica (SCH), o Hackathon DataQuest e o Hackathon de Finanças. Ao conectar empresas a essas plataformas, ajudo-as a interagir com os estudantes mais brilhantes de Marrocos e a impulsionar o desenvolvimento de futuros talentos.' },
            { id: 'rubiks-club', title: "Clube do Cubo de Rubik da UM6P", role: "Presidente", description: "Como Presidente, liderei as atividades do clube, organizei workshops e promovi uma comunidade de solucionadores de problemas." },
            { id: 'eplus-club', title: "Clube E++, EMINES", role: "Gerente de Patrocínios", description: "Consegui patrocinadores para a Competição Nacional de Ciência de Dados (NDSC) e a Competição de Robô Inteligente (IRC) entrando em contato com parceiros potenciais, apresentando propostas e garantindo seu apoio para os dois eventos." },
            { id: 'eastro-club', title: "Clube de E-Astronomia, EMINES", role: "Gerente de Logística", description: "Organizei a logística para noites de observação e seminários educacionais, garantindo a disponibilidade impecável de todos os equipamentos e recursos, e atuei como especialista em astronomia no Dia Marroquino de Matemática." },
            { id: 'rotaract-club', title: "Clube ROTARACT EMINES", role: "Gerente de Comunicação e Conteúdo", description: "Gerenciei a comunicação do clube e a criação de conteúdo, desenvolvendo materiais envolventes para promover as atividades, eventos e iniciativas do Rotaract EMINES." },
            { id: 'pingpong-club', title: "Clube de Tênis de Mesa da UM6P", role: "Gerente de Logística", description: "Organizei torneios e sessões de treinamento, cuidando de todos os aspectos logísticos, desde o agendamento até a gestão de equipamentos. " },
            { id: 'university-sports', title: "Esportes Universitários", role: "Jogador das equipes de Handebol, Voleibol e Futebol", description: "Como membro ativo de várias equipes esportivas universitárias, desenvolvi fortes habilidades de trabalho em equipe, disciplina e liderança." }
        ],
    },
    de: {
        page_title: "Mohammed EL BARAKA - Industrielles Management & Datenwissenschaft",
        nav_about: "Über mich",
        nav_projects: "Projekte",
        nav_skills: "Fähigkeiten",
        nav_leadership: "Aktivitäten",
        nav_contact: "Kontakt",
        hero_title: "Industrielles Management,<br>& Datenwissenschaft",
        hero_typing: ["Industrielles Management", "Datenwissenschaft"],
        hero_subtitle: "Ein Wirtschaftsingenieur-Absolvent der EMINES-UM6P, spezialisiert auf Industrielles Management, mit einer Leidenschaft für Optimierung, Datenwissenschaft und den Einsatz von Technologie zur Lösung realer Herausforderungen.",
        hero_cta_button: "Meine Arbeit ansehen",
        about_title: "Über mich",
        about_p1: "Hallo! Ich bin Mohammed EL BARAKA, ein Wirtschaftsingenieur-Absolvent der renommierten Mohammed VI Polytechnic University (UM6P). Mein akademischer Weg, der mit einem intensiven Vorbereitungsprogramm in Mathematik und Physik begann, hat mir ein starkes analytisches Denken und Problemlösungskompetenz verliehen.",
        about_p2: "Mich reizt die Herausforderung, komplexe Probleme zu lösen, insbesondere durch den Einsatz von Datenwissenschaft, maschinellem Lernen und Optimierungsalgorithmen. Meine Arbeitsphilosophie besteht darin, die Lücke zwischen theoretischem Wissen und praktischer Anwendung zu schließen, um greifbare Ergebnisse zu erzielen.",
        about_p3: "Ich bin eine proaktive Führungspersönlichkeit, spreche fließend Arabisch, Französisch und Englisch und bin stets bestrebt zu lernen, zusammenzuarbeiten und meine Fähigkeiten in wirkungsvollen Projekten einzusetzen.",
        view_resume_button: "📄 Lebenslauf ansehen",
        projects_title: "Meine Projekte",
        skills_title: "Technische Fähigkeiten",
        leadership_title: "Aktivitäten & Führung",
        contact_title: "Kontakt aufnehmen",
        contact_subtitle: "Ich bin immer offen für neue Projekte, kreative Ideen oder Möglichkeiten. Lassen Sie uns in Kontakt treten.",
        contact_button: "Kontaktieren Sie mich",
        footer_text: `© ${new Date().getFullYear()} Mohammed EL BARAKA. Alle Rechte vorbehalten.`,
        contact_modal_title: "Kontakt aufnehmen",
        contact_modal_email: "E-Mail senden",
        contact_modal_whatsapp: "Auf WhatsApp schreiben",
        contact_modal_call: "Anrufen",
        project_button_report: "Bericht",
        project_button_presentation: "Präsentation",
        project_button_explain: "✨ Erklären",
        project_button_summarize: "✨ Zusammenfassen",
        modal_explaining_title: `✨ Erklärung: {title}`,
        modal_summarizing_title: `✨ Zusammenfassung: {title}`,
        modal_skill_projects_title: `🚀 Projekte mit {skill}`,
        modal_list_intro: `Hier sind die Projekte, bei denen ich <strong>{skill}</strong> verwendet habe:`,
        pdf_modal_title_report: `Bericht - {title}`,
        pdf_modal_title_presentation: `Präsentation - {title}`,
        pdf_modal_title_resume: `Mein Lebenslauf`,
        projects: [
            { id: 'mental-health-analytics', title: 'Prädiktive Analytik für studentische mentale Gesundheit', description: 'Entwicklung prädiktiver Modelle unter Verwendung von Fragebogen- und Textdaten zur Bewertung der mentalen Gesundheit von Studenten, mit hoher Genauigkeit bei der Vorhersage von Angst-, Depressions- und Stressniveaus.' },
            { id: 'red-fruit-optimization', title: 'Optimierung der Beerenobstproduktion', description: 'Entwurf und Implementierung eines linearen Programmierungsmodells zur Gewinnmaximierung für die Beerenobstproduktion in Gewächshäusern unter Berücksichtigung verschiedener Einschränkungen und Szenarien.' },
            { id: 'powerbi-dashboard', title: 'Integration von Kontoauszügen mit Power BI', description: 'Entwicklung eines interaktiven Power BI-Dashboards zur Integration und Visualisierung wichtiger Finanzkennzahlen aus Kontoauszügen und Lieferscheinen für eine vernetzte Datenansicht.' },
            { id: 'rsa-cryptography', title: 'Angriffe gegen Shared-Module RSA', description: 'Untersuchung und Simulation von Angriffen auf das RSA-Kryptosystem mit Fokus auf Schwachstellen durch gemeinsam genutzte Module zur Demonstration kryptografischer Schwachstellen.' },
            { id: 'biomedical-diffusion', title: 'Sauerstoffdiffusion im Lungenazinus', description: 'Durchführung eines biomedizinischen Projekts zur Modellierung der Sauerstoffdiffusion im Lungenazinus durch numerische Lösung der 2D-Diffusionsgleichung.' },
            { id: 'robotics-vision', title: 'Robotik und Bilderkennung', description: 'Entwicklung eines kompletten Robotersystems mit Bilderkennungsfunktionen, von der 3D-Modellierung in SolidWorks bis zur Implementierung von Bildverarbeitungsalgorithmen in Python.' }
        ],
        leadership: [
            { id: 'emines-junior-entreprise', title: 'Emines Junior Entreprise (EJE)', role: 'Sponsoring-Manager', description: 'Als Sponsoring-Manager liegt meine Hauptverantwortung in der Sicherung wichtiger Partnerschaften und Sponsorings zur Finanzierung der studentischen Hackathons von EJE. Ich suche aktiv Sponsoren für Großveranstaltungen wie den OP&X Hackathon, den Strategic Consulting Hackathon (SCH), den DataQuest Hackathon und den Finance Hackathon. Durch die Verbindung von Unternehmen mit diesen Plattformen helfe ich ihnen, mit Marokkos klügsten Köpfen in Kontakt zu treten.' },
            { id: 'rubiks-club', title: "UM6P Rubik's Cube Club", role: "Präsident", description: "Als Präsident leitete ich die Aktivitäten des Clubs, organisierte Workshops und geförderte eine Gemeinschaft von Problemlösern." },
            { id: 'eplus-club', title: "E++ Club, EMINES", role: "Sponsoring-Manager", description: "Gewinnung von Sponsoren für die National Data Science Competition (NDSC) und die Intelligent Robot Competition (IRC) durch Kontaktaufnahme mit potenziellen Partnern, Präsentation von Vorschlägen und Sicherstellung ihrer Unterstützung für beide Veranstaltungen." },
            { id: 'eastro-club', title: "E-Astronomy Club, EMINES", role: "Logistik-Manager", description: "Ich koordinierte die Logistik für Beobachtungsnächte und Bildungsseminare, stellte die nahtlose Verfügbarkeit aller Geräte und Ressourcen sicher und war als Astronomieexperte am marokkanischen Tag der Mathematik tätig." },
            { id: 'rotaract-club', title: "ROTARACT EMINES Club", role: "Kommunikations- & Content-Manager", description: "Ich leitete die Kommunikation und Inhaltserstellung des Clubs und entwickelte ansprechende Materialien zur Förderung der Aktivitäten, Veranstaltungen und Initiativen von Rotaract EMINES." },
            { id: 'pingpong-club', title: "UM6P Ping Pong Club", role: "Logistik-Manager", description: "Ich organisierte Turniere und Trainingseinheiten und kümmerte sich um alle logistischen Aspekte von der Terminplanung bis zur Geräteverwaltung." },
            { id: 'university-sports', title: "Universitätssport", role: "Spieler der Handball-, Volleyball- und Fußballmannschaften", description: "Als aktives Mitglied mehrerer Universitätssportteams habe ich starke Fähigkeiten in Teamarbeit, Disziplin und Führung entwickelt." }
        ],
        help_button: "Wie kann ich helfen?",
        help_modal_title: "Beschreiben Sie Ihren Bedarf",
        help_modal_placeholder: "Erzählen Sie mir von dem Projekt, der Herausforderung oder der Rolle, die Sie im Sinn haben. Zum Beispiel: 'Ich brauche jemanden, der ein prädiktives Modell für Kundendaten erstellt' oder 'Ich suche einen Projektmanager mit technischem Hintergrund.'",
        help_modal_submit: "Bedarf analysieren",
        help_modal_response_title: "So kann ich helfen",
        contact_button_after_ai: "Mohammed kontaktieren"
    }
};

const projectsData = [
    { id: 'mental-health-analytics', technologies: ['Machine Learning', 'NLP', 'Python', 'Scikit-learn', 'NLTK', 'Classification Models'], reportUrl: 'https://drive.google.com/file/d/1HOFF_SywL49TlsOnuertwlaaWZrOq8Vn/view?usp=sharing', presentationUrl: 'https://drive.google.com/file/d/1N2X0nVZxP2OwwLzlIdJ-LYeLmeGt4_uu/view?usp=drive_link' },
    { id: 'red-fruit-optimization', technologies: ['Linear Programming', 'Python', 'Pulp', 'Optimization Modeling', 'Algorithm Design'], reportUrl: 'https://drive.google.com/file/d/1pU34qkKTJsIPJPAfX8AUcACUQAjINbOG/view?usp=sharing', presentationUrl: 'https://drive.google.com/file/d/11yrl2LQlbk03yFPFXyaRRbM6juZFemUd/view?usp=sharing' },
    { id: 'powerbi-dashboard', technologies: ['Power BI', 'Excel', 'Data Analysis', 'Dashboard Design', 'VBA'], reportUrl: 'https://drive.google.com/file/d/1hprde0Kd4Tsi4D9BBQsdlpKLj5D3WIFj/view?usp=sharing', presentationUrl: 'https://drive.google.com/file/d/1JH7sEdd0Ulb_Hs9c1dNfDMbdE7s8jpXa/view?usp=sharing' },
    { id: 'rsa-cryptography', technologies: ['Cryptography', 'RSA Algorithm', 'Cryptanalysis', 'Number Theory', 'SageMath', 'Python'], reportUrl: 'https://drive.google.com/file/d/1e3hIOIsfj5ZOvqIK-ey-Bew5HXZwI69l/view?usp=sharing', presentationUrl: 'https://drive.google.com/file/d/14zBJ0cRRHfBgGoerNRfXe2z7y9sv5oZ-/view?usp=sharing' },
    { id: 'biomedical-diffusion', technologies: ['Mathematical Modeling', 'Numerical Methods', 'Python', 'NumPy', 'SciPy', 'Matplotlib'], reportUrl: 'https://drive.google.com/file/d/1X9aQBQ8qnkGaZF9ZD9vQb4T_A_D5GYnT/view?usp=sharing', presentationUrl: 'https://drive.google.com/file/d/1SOKxBawlC51whiwh9lZ1I8KE1WcRuN7L/view?usp=sharing' },
    { id: 'robotics-vision', technologies: ['Robotics', 'Python', 'Image Detection', 'SolidWorks', 'OpenCV'], reportUrl: 'https://drive.google.com/file/d/148jUa5mRyydjS2Ht8fpk8rGQDJ9yQJok/view?usp=sharing', presentationUrl: 'https://drive.google.com/file/d/1VI5hfPQouqk4th9hAxw9NYShz_brn1Pi/view?usp=sharing' }
];

const skillsData = [ 'Python', 'Java', 'C', 'JavaScript', 'Bash', 'SQL', 'HTML', 'CSS', 'Machine Learning', 'Data Analysis', 'NLP', 'Optimization Algorithms', 'Linear Programming', 'Power BI', 'VBA', 'Excel', 'Robotics', 'SolidWorks', 'QGIS', 'Image Detection', 'Cryptography', 'Cybersecurity', 'Pentesting Tools', 'Django', 'SageMath', 'Manim', 'Overleaf', 'Git', 'AI Prompt Engineering' ];

const skillDescriptions = {
    en: {
        'Python': 'Python is my primary programming language, used across all my key projects for machine learning models, mathematical modeling, automation scripts, and image processing.',
        'Java': 'Java was used during my engineering coursework to build structured, object-oriented applications, reinforcing my software design and algorithmic foundation.',
        'C': 'C is the foundation of my programming knowledge, used for low-level systems programming, embedded firmware in robotics, and optimizing memory-critical algorithms.',
        'JavaScript': 'JavaScript powers the interactive features and dynamic animations of this portfolio website, as well as web applications utilizing frontend functionality.',
        'Bash': 'Bash scripting allows me to automate environment setup, task execution, and file management in Unix/Linux systems for data workflows.',
        'SQL': 'SQL is essential for querying, structuring, and managing relational databases to extract meaningful insights for data analysis pipelines.',
        'HTML': 'HTML is used to build the structural semantic foundation of my web interfaces, ensuring accessibility and compliance with SEO standards.',
        'CSS': 'CSS styling enables the visual layout, responsive design, custom animations, and glassmorphism elements across my web projects.',
        'Machine Learning': 'Applied in my Student Mental Health Analytics project to train classification models (using Scikit-learn) predicting anxiety, depression, and stress levels from text and survey data.',
        'Data Analysis': 'Used in financial dashboard integrations and predictive modeling projects to clean, transform, and uncover key patterns within complex datasets.',
        'NLP': 'Implemented in my Student Mental Health Analytics project using NLTK and text processing algorithms to extract features and analyze sentiments from student feedback.',
        'Optimization Algorithms': 'Key tool in industrial management for maximizing resource efficiency, routing, and operations layout, applied using both standard algorithms and custom heuristics.',
        'Linear Programming': 'Used in the Red Fruit Production Optimization project to build LP models that maximize greenhouse profits under strict resource constraints using PuLP.',
        'Power BI': 'Employed to design and develop interactive financial dashboards, integrating banking statements, delivery notes, and transaction metrics for centralized business intelligence.',
        'VBA': 'Used to automate Excel report generation, data parsing, and administrative macro workflows, streamlining repetitive operations in data management.',
        'Excel': 'My foundational tool for organizing financial spreadsheets, analyzing data, and preparing datasets prior to Power BI dashboards integration or ML pipelines.',
        'Robotics': 'Demonstrated in my Robotics & Image Detection project, involving mechanical design, physical prototyping, and motor coordination scripts for automated tasks.',
        'SolidWorks': 'Used for the 3D computer-aided design (CAD) of mechanical components, robotic assemblies, and structure modeling in engineering courses and physical projects.',
        'QGIS': 'Used in spatial data analysis, mapping agricultural areas, and industrial logistics pathfinding to visualize and manage geographic information systems (GIS).',
        'Image Detection': 'Implemented in my Robotics project using OpenCV in Python to detect, track, and interact with objects in real-time video streams.',
        'Cryptography': 'Studied theoretical cryptographic foundations and vulnerabilities, successfully simulating advanced modular arithmetic attacks against cryptosystems like RSA.',
        'Cybersecurity': 'Explored secure systems design, encryption protocols, network vulnerabilities, and defensive programming to protect application infrastructures.',
        'Pentesting Tools': 'Utilized in laboratory environments to test system security, identify configuration vulnerabilities, and understand how to defend networks against malicious attacks.',
        'Django': 'Used to build robust, secure, and database-driven web application backends, integrating Python scripts and analytical tools into responsive web portals.',
        'SageMath': 'Applied in cryptanalysis and algebraic coding theory to perform complex modular arithmetic and number theory calculations, notably in simulating attacks on RSA.',
        'Manim': 'Used to generate mathematical and algorithm animations, turning complex industrial engineering concepts into highly intuitive educational videos.',
        'Overleaf': 'My preferred platform for drafting professional academic reports, research papers, and technical project documentation in LaTeX.',
        'Git': 'Essential for version control, tracking codebase changes, and collaborating on academic and software projects via repository platforms.',
        'AI Prompt Engineering': 'Practiced in project optimization and workflow acceleration to effectively integrate LLMs and prompt techniques for serverless assistant integrations.'
    },
    fr: {
        'Python': 'Python est mon langage de programmation principal, utilisé dans tous mes projets clés pour les modèles d\'apprentissage automatique, la modélisation mathématique, l\'automatisation et le traitement d\'images.',
        'Java': 'Java a été utilisé lors de mes cours d\'ingénieur pour créer des applications structurées orientées objet, renforçant mes bases en conception logicielle et en algorithmique.',
        'C': 'C est la base de mes connaissances en programmation, utilisé pour la programmation système de bas niveau, les micrologiciels embarqués en robotique et l\'optimisation d\'algorithmes critiques en mémoire.',
        'JavaScript': 'JavaScript alimente les fonctionnalités interactives et les animations dynamiques de ce site portfolio, ainsi que les applications web utilisant des fonctionnalités frontend.',
        'Bash': 'Les scripts Bash me permettent d\'automatiser la configuration de l\'environnement, l\'exécution des tâches et la gestion des fichiers dans les systèmes Unix/Linux pour les flux de données.',
        'SQL': 'SQL est essentiel pour requêter, structurer et gérer les bases de données relationnelles afin d\'extraire des informations significatives pour les pipelines d\'analyse de données.',
        'HTML': 'HTML est utilisé pour construire la base sémantique structurelle de mes interfaces web, garantissant l\'accessibilité et la conformité aux normes SEO.',
        'CSS': 'Le style CSS permet la mise en page visuelle, le design adaptatif, les animations personnalisées et les éléments de glassmorphisme dans mes projets web.',
        'Machine Learning': 'Appliqué dans mon projet d\'Analyse Prédictive de la Santé Mentale des Étudiants pour entraîner des modèles de classification (via Scikit-learn) prédisant l\'anxiété, la dépression et le stress à partir de données textuelles et d\'enquêtes.',
        'Data Analysis': 'Utilisé dans les intégrations de tableaux de bord financiers et les projets de modélisation prédictive pour nettoyer, transformer et découvrir des modèles clés au sein d\'ensembles de données complexes.',
        'NLP': 'Mis en œuvre dans mon projet d\'Analyse Prédictive de la Santé Mentale des Étudiants à l\'aide de NLTK et d\'algorithmes de traitement de texte pour extraire des caractéristiques et analyser les sentiments des commentaires des étudiants.',
        'Optimization Algorithms': 'Outil clé en gestion industrielle pour maximiser l\'efficacité des ressources, le routage et l\'aménagement des opérations, appliqué à l\'aide d\'algorithmes standards et d\'heuristiques personnalisées.',
        'Linear Programming': 'Utilisé dans le projet d\'Optimisation de la Production de Fruits Rouges pour construire des modèles de programmation linéaire maximisant les profits des serres sous des contraintes de ressources strictes avec PuLP.',
        'Power BI': 'Employé pour concevoir et développer des tableaux de bord financiers interactifs, en intégrant les relevés bancaires, les bons de livraison et les indicateurs de transaction pour une intelligence d\'affaires centralisée.',
        'VBA': 'Utilisé pour automatiser la génération de rapports Excel, l\'analyse des données et les flux de macro administratifs, simplifiant les opérations répétitives dans la gestion des données.',
        'Excel': 'Mon outil fondamental pour organiser les feuilles de calcul financières, analyser les données et préparer les ensembles de données avant l\'intégration des tableaux de bord Power BI ou des pipelines ML.',
        'Robotics': 'Démontré dans mon projet de Robotique et Détection d\'Images, impliquant la conception mécanique, le prototypage physique et les scripts de coordination des moteurs pour les tâches automatisées.',
        'SolidWorks': 'Utilisé pour la conception assistée par ordinateur 3D (CAO) de composants mécaniques, d\'assemblages robotiques et de modélisation de structures dans les cours d\'ingénierie et les projets physiques.',
        'QGIS': 'Utilisé dans l\'analyse de données spatiales, la cartographie des zones agricoles et la recherche d\'itinéraires logistiques industriels pour visualiser et gérer les systèmes d\'information géographique (SIG).',
        'Image Detection': 'Mis en œuvre dans mon projet de robotique à l\'aide d\'OpenCV en Python pour détecter, suivre et interagir avec des objets dans des flux vidéo en temps réel.',
        'Cryptography': 'Étude des fondements cryptographiques théoriques et des vulnérabilités, simulant avec succès des attaques d\'arithmétique modulaire avancées contre des cryptosystèmes comme RSA.',
        'Cybersecurity': 'Exploration de la conception de systèmes sécurisés, des protocoles de chiffrement, des vulnérabilités réseau et de la programmation défensive pour protéger les infrastructures d\'applications.',
        'Pentesting Tools': 'Utilisé dans des environnements de laboratoire pour tester la sécurité des systèmes, identifier les vulnérabilités de configuration et comprendre comment défendre les réseaux contre les attaques malveillantes.',
        'Django': 'Utilisé pour créer des backends d\'applications web robustes, sécurisés et basés sur des bases de données, en intégrant des scripts Python et des outils analytiques dans des portails web réactifs.',
        'SageMath': 'Appliqué en cryptanalyse et en théorie des codes algébriques pour effectuer des calculs complexes d\'arithmétique modulaire et de théorie des nombres, notamment dans la simulation d\'attaques sur RSA.',
        'Manim': 'Utilisé pour générer des animations mathématiques et algorithmiques, transformant des concepts complexes de génie industriel en vidéos éducatives hautement intuitives.',
        'Overleaf': 'Ma plateforme préférée pour rédiger des rapports académiques professionnels, des articles de recherche et de la documentation technique de projet en LaTeX.',
        'Git': 'Essentiel pour le contrôle de version, le suivi des modifications de code et la collaboration sur des projets académiques et logiciels via des plateformes de référentiel.',
        'AI Prompt Engineering': 'Pratiqué dans l\'optimisation des projets et l\'accélération des flux de travail pour intégrer efficacement les LLM et les techniques de prompt pour les intégrations d\'assistants serverless.'
    }
};

const leadershipData = [
     { id: 'emines-junior-entreprise', imageUrl: 'https://via.placeholder.com/600x400.png/1F1F1F/A78BFA?text=EJE' },
     { id: 'rubiks-club', imageUrl: 'https://via.placeholder.com/600x400.png/1F1F1F/A78BFA?text=Rubiks+Club' },
     { id: 'eplus-club', imageUrl: 'https://via.placeholder.com/600x400.png/1F1F1F/A78BFA?text=E++Club' },
     { id: 'eastro-club', imageUrl: 'https://via.placeholder.com/600x400.png/1F1F1F/A78BFA?text=Astronomy+Club' },
     { id: 'rotaract-club', imageUrl: 'https://via.placeholder.com/600x400.png/1F1F1F/A78BFA?text=Rotaract' },
     { id: 'pingpong-club', imageUrl: 'https://via.placeholder.com/600x400.png/1F1F1F/A78BFA?text=PingPong+Club' },
     { id: 'university-sports', imageUrl: 'https://via.placeholder.com/600x400.png/1F1F1F/A78BFA?text=Sports' }
];

const toggleLabels = {
    en: { more: "See More", less: "See Less" },
    fr: { more: "Voir Plus", less: "Voir Moins" },
    ar: { more: "عرض المزيد", less: "عرض أقل" },
    es: { more: "Ver Más", less: "Ver Menos" },
    de: { more: "Mehr anzeigen", less: "Weniger anzeigen" },
    zh: { more: "查看更多", less: "收起" },
    pt: { more: "Ver Mais", less: "Ver Menos" }
};
